export const userTypes = {



    ADMIN_GET_SINGLE_CUSTOMER: 'ADMIN_GET_SINGLE_CUSTOMER',
    ADMIN_GET_SINGLE_FULFILMENT: 'ADMIN_GET_SINGLE_FULFILMENT',

    OPEN_CONNECT_ACCOUNT_MODAL: 'OPEN_CONNECT_ACCOUNT_MODAL',
    CLOSE_CONNECT_ACCOUNT_MODAL: 'CLOSE_CONNECT_ACCOUNT_MODAL',

    OPEN_MOBILE_ACCOUNT_MODAL: 'OPEN_MOBILE_ACCOUNT_MODAL',
    CLOSE_MOBILE_ACCOUNT_MODAL: 'CLOSE_MOBILE_ACCOUNT_MODAL'


}